username = input("Введите Ваше имя: ")
title1 = input('Введите заголовок заметки 1: ')
title2 = input('Введите заголовок заметки 2: ')
title3 = input('Введите заголовок заметки 3: ')
titles = [title1, title2, title3]
content = input("Введите описание заметки: ")
status = input("Введите статус заметки: ")
created_date = input('Введите дату начала в формате \"дата-месяц-год\": ')
issue_date = input('Введите дату окончания в формате \"дата-месяц-год\": ')
print('Имя пользователя: ', username)
print('Заголовок заметки: ', titles)
print('Описание заметки: ', content)
print('Статус заметки: ', status)
print('Дата создания заметки: ', created_date)
print('Дата истечения заметки: ', issue_date)