username = input("Введите Ваше имя: ")
title = input("Введите заголовок заметки: ")
content1 = input("Основные темы: ")
content2 = input("Персонажи: ")
content3 = input("Рекомендации для чтения: ")
content = [content1, content2, content3]
status = input("Введите статус заметки: ")
created_date = input('Введите дату начала в формате \"дата-месяц-год\": ')
issue_date = input('Введите дату окончания в формате \"дата-месяц-год\": ')
print('Имя пользователя: ', username)
print('Заголовок заметки: ', title)
print('Описание заметки: ', content)
print('Статус заметки: ', status)
print('Дата создания заметки: ', created_date)
print('Дата истечения заметки: ', issue_date)
